import environ

env = environ.Env()
env.read_env('.env')
REDIS_PORT = env('REDIS_PORT')
DJANGO_PORT = env('DJANGO_PORT')
MONGODB_PORT = env('MONGODB_PORT')
MODE = env('MODE')
DJANGO_ALLOWED_HOSTS = env('DJANGO_ALLOWED_HOSTS')
MONGODB_ALLOWED_HOSTS = env('MONGODB_ALLOWED_HOSTS')
CELERY_BROKER = env('CELERY_BROKER')
CELERY_BACKEND = env('CELERY_BACKEND')
TASK_DATABSE = env('TASK_DATABSE')
SCRAPE_DATABASE = env('SCRAPE_DATABASE')
